---
# tasks file for nrser.rbenv_gem

- include: all.yml
  when: rbenv_gem_rubies == 'all'

- include: global.yml
  when: rbenv_gem_rubies == 'global'

- include: repo-source.yml
  when: rbenv_gem_repo is defined

- include: remote-source.yml
  when: rbenv_gem_repo is not defined
