---
# tasks file for nrser.rbenv_gem

- include: all.yml
  when: rbenv_gem_rubies == 'all'

- include: global.yml
  when: rbenv_gem_rubies == 'global'

# this will clone the repo, build the .gem and point rbenv_gem_source to it
- include: clone-repo.yml
  when: rbenv_gem_repo is defined

- include: manage-source.yml
  when: rbenv_gem_source is defined

- include: manage-version.yml
  when: rbenv_gem_source is not defined
