---
# included when rbenv_gem_repo is defined
# clones out the repo to a temp location, builds the .gem file, and installs

- name: set rbenv_gem_repo_dir fact
  set_fact:
    rbenv_gem_repo_dir: /tmp/ansible-nrser.rbenv_gem/{{ rbenv_gem_name }}-{{ rbenv_gem_version }}

- name: set rbenv_gem_gem_source fact
  set_fact:
    rbenv_gem_gem_source: "{{ rbenv_gem_repo_dir }}/{{ rbenv_gem_name }}-{{ rbenv_gem_version }}.gem"

- name: check out {{ rbenv_gem_repo }}@v{{ rbenv_gem_version }}
  git:
    repo: "{{ rbenv_gem_repo }}"
    dest: "{{ rbenv_gem_repo_dir }}"
    version: "v{{ rbenv_gem_version }}"
    depth: 1
    update: false

- command: gem build {{ rbenv_gem_name }}.gemspec
  args:
    chdir: "{{ rbenv_gem_repo_dir }}"
    creates: "{{ rbenv_gem_gem_source }}"

- name: manage {{ rbenv_gem_name }} gem in rbenv rubies
  gem:
    name: "{{ rbenv_gem_name }}"
    user_install: "{{ rbenv_gem_user_install }}"
    state: "{{ rbenv_gem_state }}"
    executable: "{{ ansible_env.HOME }}/.rbenv/versions/{{ item }}/bin/gem"
    gem_source: "{{ rbenv_gem_gem_source }}"
  when: item != 'system'
  with_items: rbenv_gem_rubies

- name: manage {{ rbenv_gem_name }} gem in system ruby
  gem:
    name: "{{ rbenv_gem_name }}"
    user_install: "{{ rbenv_gem_user_install }}"
    state: "{{ rbenv_gem_state }}"
    executable: /usr/bin/gem
    gem_source: "{{ rbenv_gem_gem_source }}"
  sudo: true
  when: item == 'system'
  with_items: rbenv_gem_rubies